### PR TITLE
Merge bower code into master

### PR DESCRIPTION
**Pull request by chrisisbeef**
Let's merge your bower stuff into the primary repo so it stay up to date with future releases.

### CODE REVIEW

**Comment by chrisisbeef** [comment]
@robertdmunn - Can you take a look and try to resolve whatever conflicts exist so we can merge this in?

**Comment by chrisisbeef** [comment]
Just noting that this is to address request #11

**Comment by robertdmunn** [comment]
yes

**Comment by robertdmunn** [comment]
I just synched my fork with your master. Please let me know if I need to do anything else.

Robert

**Pull request merged**
